### ISSUE TITLE
ActiveFedora 6.7.4 doesn't work with rubydora 1.7.0

### ISSUE THREAD

**Issue by jcoyne** [samvera/active_fedora#332]
```
 NoMethodError:
   undefined method `new_record?' for #<ActiveFedora::UnsavedDigitalObject:0x007f8f38510a58>
 # /Users/justin/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/rubydora-1.7.0/lib/rubydora/datastream.rb:122:in `new?'
 # /Users/justin/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/active-fedora-6.7.4/lib/active_fedora/rdf_datastream.rb:75:in `deserialize'
```
